GET http://localhost:3000/expenses

###

GET http://localhost:3000/expenses/61db4726d7036b155bbbd69a

###

POST http://localhost:3000/expenses
Content-Type: application/json

{
    "date": "1999-12-30",
    "title": "Gummi",
    "price": 100,
    "category": "Hemmet"
}

###

DELETE http://localhost:3000/expenses/61dc330222ec110877a87b4b

###

PUT  http://localhost:3000/expenses/61db4726d7036b155bbbd69a
Content-Type: application/json

{
    "date": "1900-01-01",
    "title": "Gummiband",
    "price": 10000,
    "category": "Nöje"
}